<nav class="navbar navbar-default navbar-fixed-top navbar-inverse" role="navigation">
	<div class="navbar-header">
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
			<span class="sr-only"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>
    	<a class="navbar-brand" href="#"><fmt:message key="application.title" /></a>
  	</div>
  	<div class="collapse navbar-collapse" id="navbar-collapse-1">
    	<ul class="nav navbar-nav">
      		<li><a href="#database"><fmt:message key="module.database" /></a></li>
      		<li><a href="#campaign"><fmt:message key="module.campaign" /></a></li>
      		<li><a href="#report"><fmt:message key="module.report" /></a></li>
      		<li><a href="#setting"><fmt:message key="module.setting" /></a></li>
    	</ul>
  	</div>
</nav>