/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.16
 * Generated at: 2014-02-08 12:49:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.apps.database;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/apps/database/main.js.jsp", Long.valueOf(1391863771854L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      com.pet.email.web.util.WebConstants WebConstants = null;
      WebConstants = (com.pet.email.web.util.WebConstants) _jspx_page_context.getAttribute("WebConstants", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (WebConstants == null){
        WebConstants = new com.pet.email.web.util.WebConstants();
        _jspx_page_context.setAttribute("WebConstants", WebConstants, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write("\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("\t<div class=\"pull-right\">\r\n");
      out.write("\t\t<button class=\"btn btn-primary\" type=\"button\" id=\"database-new-btn\">New</button>\r\n");
      out.write("\t\t<button class=\"btn btn-primary\" type=\"button\">Import</button>\r\n");
      out.write("\t\t<button class=\"btn btn-danger\" type=\"button\" id=\"database-del-btn\">Delete</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<span class=\"clearfix\"></span>\r\n");
      out.write("\t<hr />\r\n");
      out.write("\t<table class=\"table table-bordered table-striped\" id=\"database-table\">\r\n");
      out.write("\t\t<thead>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th width=\"10px\"><input type=\"checkbox\" name=\"check_all\" value=\"1\" /></th>\r\n");
      out.write("\t\t\t\t<th>ID</th>\r\n");
      out.write("\t\t\t\t<th>Name</th>\r\n");
      out.write("\t\t\t\t<th>Description</th>\r\n");
      out.write("\t\t\t\t<th>Date Created</th>\r\n");
      out.write("\t\t\t\t<th>Status</th>\r\n");
      out.write("\t\t\t\t<th>Type</th>\r\n");
      out.write("\t\t\t\t<th>Size</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</thead>\r\n");
      out.write("\t\t<tbody>\r\n");
      out.write("\t\t</tbody>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<div class=\"pull-right\">\r\n");
      out.write("\t\t<ul class=\"pagination\">\r\n");
      out.write("\t  \t\t<li><a>&laquo;</a></li>\r\n");
      out.write("\t  \t\t<li><a>1</a></li>\r\n");
      out.write("\t  \t\t<li><a>2</a></li>\r\n");
      out.write("\t  \t\t<li><a>3</a></li>\r\n");
      out.write("\t  \t\t<li><a>4</a></li>\r\n");
      out.write("\t  \t\t<li><a>5</a></li>\r\n");
      out.write("\t  \t\t<li><a>&raquo;</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"modal fade bs-modal-lg\" id=\"add-database-modal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("\t<div class=\"modal-dialog modal-lg\">\r\n");
      out.write("    \t<div class=\"modal-content\">\r\n");
      out.write("    \t\t<div class=\"modal-header\">\r\n");
      out.write("        \t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">&times;</button>\r\n");
      out.write("        \t\t<h4 class=\"modal-title\" id=\"myModalLabel\">New Database</h4>\r\n");
      out.write("      \t\t</div>\r\n");
      out.write("      \t\t<div class=\"modal-body\">\r\n");
      out.write("        \t\t<form class=\"form-horizontal\" role=\"form\">\r\n");
      out.write("        \t\t\t<div class=\"form-group\">\r\n");
      out.write("    \t\t\t\t\t<label for=\"database-name\" class=\"col-sm-2 control-label\">Name</label>\r\n");
      out.write("    \t\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("      \t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"database-name\" placeholder=\"Name\">\r\n");
      out.write("    \t\t\t\t\t</div>\r\n");
      out.write("  \t\t\t\t\t</div>\r\n");
      out.write("  \t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("    \t\t\t\t\t<label for=\"database-description\" class=\"col-sm-2 control-label\">Description</label>\r\n");
      out.write("    \t\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("      \t\t\t\t\t\t<textarea rows=\"5\" id=\"database-description\" class=\"form-control\"></textarea>\r\n");
      out.write("    \t\t\t\t\t</div>\r\n");
      out.write("  \t\t\t\t\t</div>\r\n");
      out.write("  \t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("    \t\t\t\t\t<label for=\"database-type\" class=\"col-sm-2 control-label\">Type</label>\r\n");
      out.write("    \t\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("      \t\t\t\t\t\t<div class=\"btn-group\" data-toggle=\"buttons\">\r\n");
      out.write("  \t\t\t\t\t\t\t\t<label class=\"btn btn-default\">\r\n");
      out.write("    \t\t\t\t\t\t\t\t<input type=\"radio\" name=\"database-type\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${WebConstants.DATABASE_TYPE_SUBSCRIBE}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"> Subscription\r\n");
      out.write("  \t\t\t\t\t\t\t\t</label>\r\n");
      out.write("  \t\t\t\t\t\t\t\t<label class=\"btn btn-default\">\r\n");
      out.write("    \t\t\t\t\t\t\t\t<input type=\"radio\" name=\"database-type\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${WebConstants.DATABASE_TYPE_UNSUBSCRIBE}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"> Unsubscribe\r\n");
      out.write("  \t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t\t</div>\r\n");
      out.write("  \t\t\t\t\t</div>\r\n");
      out.write("        \t\t</form>\r\n");
      out.write("      \t\t</div>\r\n");
      out.write("      \t\t<div class=\"modal-footer\">\r\n");
      out.write("        \t\t<button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("        \t\t<button type=\"button\" class=\"btn btn-primary\" id=\"add-database-save-btn\">Save</button>\r\n");
      out.write("      \t\t</div>\r\n");
      out.write("    \t</div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/JavaScript\">\r\n");
      out.write("\tvar $newBtn = $(\"#database-new-btn\");\r\n");
      out.write("\tvar $newDBModal = $(\"#add-database-modal\");\r\n");
      out.write("\tvar $table = $(\"#database-table\");\r\n");
      out.write("\tvar $deleteBtn = $(\"#database-del-btn\");\r\n");
      out.write("\tvar selectedIds = [];\r\n");
      out.write("\tloadDatabaseList();\r\n");
      out.write("\t\r\n");
      out.write("\t$deleteBtn.unbind(\"click\");\r\n");
      out.write("\t$deleteBtn.click(function() {\r\n");
      out.write("\t\tif(selectedIds.length <= 0) {\r\n");
      out.write("\t\t\talert(\"Please select something...\");\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tdoDeleteContact(selectedIds.join(\",\"));\r\n");
      out.write("\t\t\tselectedIds = [];\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tfunction doDeleteContact(ids) {\r\n");
      out.write("\t\tvar url = 'database?");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${WebConstants.ACTION_NAME}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write('=');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${WebConstants.DO_DELETE_DATABASE}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("';\r\n");
      out.write("\t\tapp.ajaxCall({url : url, data : {ids : ids}, callbackFn : function(data, textStatus, jqXHR) {\r\n");
      out.write("\t\t\ttry {\r\n");
      out.write("\t\t\t\tvar json = $.parseJSON(jqXHR.responseText);\r\n");
      out.write("\t\t\t\tloadDatabaseList();\r\n");
      out.write("\t\t\t} catch (e) {\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t}});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction generateDBTR(database) {\r\n");
      out.write("\t\tvar status = '");
      if (_jspx_meth_fmt_005fmessage_005f0(_jspx_page_context))
        return;
      out.write("';\r\n");
      out.write("\t\tvar type = '");
      if (_jspx_meth_fmt_005fmessage_005f1(_jspx_page_context))
        return;
      out.write("';\r\n");
      out.write("\t\tif(database.active)\r\n");
      out.write("\t\t\tstatus = '");
      if (_jspx_meth_fmt_005fmessage_005f2(_jspx_page_context))
        return;
      out.write("';\r\n");
      out.write("\t\tif(database.type != '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${WebConstants.DATABASE_TYPE_SUBSCRIBE}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("')\r\n");
      out.write("\t\t\ttype = '");
      if (_jspx_meth_fmt_005fmessage_005f3(_jspx_page_context))
        return;
      out.write("';\r\n");
      out.write("\t\tvar $tr = $(\"<tr />\");\r\n");
      out.write("\t\tvar $checkbox = $(\"<input type='checkbox' name='contact-id' value='\" + database.id + \"' />\");\r\n");
      out.write("\t\tvar $checkboxTD = $(\"<td />\");\r\n");
      out.write("\t\t$checkboxTD.append($checkbox);\r\n");
      out.write("\t\tvar $idTD = $(\"<td>\"+database.id+\"</td>\");\r\n");
      out.write("\t\tvar $aName = $(\"<a>\" + app.shortened(database.name) + \"</a>\")\r\n");
      out.write("\t\tvar $nameTD = $(\"<td />\");\r\n");
      out.write("\t\t$nameTD.append($aName);\r\n");
      out.write("\t\tvar $descTD = $(\"<td>\" + app.shortened(database.description) + \"</td>\");\r\n");
      out.write("\t\tvar $dateTD = $(\"<td>\" + database.dataCreated + \"</td>\");\r\n");
      out.write("\t\tvar $statusTD = $(\"<td>\"+status+\"</td>\");\r\n");
      out.write("\t\tvar $typeTD = $(\"<td>\"+type+\"</td>\");\r\n");
      out.write("\t\tvar $sizeTD = $(\"<td>\"+database.size+\"</td>\");\r\n");
      out.write("\t\t$tr.append($checkboxTD);\r\n");
      out.write("\t\t$tr.append($idTD);\r\n");
      out.write("\t\t$tr.append($nameTD);\r\n");
      out.write("\t\t$tr.append($descTD);\r\n");
      out.write("\t\t$tr.append($dateTD);\r\n");
      out.write("\t\t$tr.append($statusTD);\r\n");
      out.write("\t\t$tr.append($typeTD);\r\n");
      out.write("\t\t$tr.append($sizeTD);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$checkbox.change(function() {\r\n");
      out.write("\t\t\tvar id = $(this).val();\r\n");
      out.write("\t\t\tif($(this).is(\":checked\"))\r\n");
      out.write("\t\t\t\tselectedIds[selectedIds.length] = id;\r\n");
      out.write("\t\t\telse {\r\n");
      out.write("\t\t\t\tselectedIds = $.grep(selectedIds, function(value) {\r\n");
      out.write("\t\t\t\t\t  return value != id;\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\treturn $tr;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction loadDatabaseList() {\r\n");
      out.write("\t\tvar url = 'database?");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${WebConstants.ACTION_NAME}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write('=');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${WebConstants.GET_DATABASE_LIST}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("';\r\n");
      out.write("\t\tapp.ajaxCall({url : url, data : null, callbackFn : function(data, textStatus, jqXHR) {\r\n");
      out.write("\t\t\ttry {\r\n");
      out.write("\t\t\t\tvar json = $.parseJSON(jqXHR.responseText);\r\n");
      out.write("\t\t\t\tvar databaseList = json.databaseList;\r\n");
      out.write("\t\t\t\tif(typeof databaseList != 'undefined' && databaseList.length > 0) {\r\n");
      out.write("\t\t\t\t\t$table.children(\"tbody\").empty();\r\n");
      out.write("\t\t\t\t\tfor(var i = 0; i < databaseList.length; i++) {\r\n");
      out.write("\t\t\t\t\t\tvar $tr = generateDBTR(databaseList[i]);\r\n");
      out.write("\t\t\t\t\t\t$table.children(\"tbody\").append($tr);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$(\"input[name=check_all]\").unbind('change');\r\n");
      out.write("\t\t\t\t\t$(\"input[name=check_all]\").change(function() {\r\n");
      out.write("\t\t\t\t\t\tvar $checkbox = $(\"input[name=contact-id]\");\r\n");
      out.write("\t\t\t\t\t\tif($(this).is(\":checked\")) {\r\n");
      out.write("\t\t\t\t\t\t\t$checkbox.prop(\"checked\", true);\r\n");
      out.write("\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t$checkbox.prop(\"checked\", false);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t$checkbox.change();\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t} catch (e) {\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t}});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t$newBtn.unbind(\"click\");\r\n");
      out.write("\t$newBtn.click(function() {\r\n");
      out.write("\t\tvar $saveBtn = $(\"#add-database-save-btn\");\r\n");
      out.write("\t\tvar $inputDesc = $(\"#database-description\");\r\n");
      out.write("\t\tvar $inputName = $(\"#database-name\");\r\n");
      out.write("\t\tvar $inputType = $(\"input[name=database-type]\");\r\n");
      out.write("\t\t$saveBtn.unbind(\"click\");\r\n");
      out.write("\t\t$inputName.val(\"\");\r\n");
      out.write("\t\t$inputDesc.val(\"\");\r\n");
      out.write("\t\t$inputType.each(function() {\r\n");
      out.write("\t\t\tif($(this).parent(\"label\").hasClass(\"active\")) {\r\n");
      out.write("\t\t\t\t$(this).parent(\"label\").removeClass(\"active\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$saveBtn.click(function() {\r\n");
      out.write("\t\t\tvar name = $inputName.val();\r\n");
      out.write("\t\t\tvar desc = $inputDesc.val();\r\n");
      out.write("\t\t\tvar type = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${WebConstants.DATABASE_TYPE_SUBSCRIBE}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("';\r\n");
      out.write("\t\t\t$inputType.each(function() {\r\n");
      out.write("\t\t\t\tif($(this).parent(\"label\").hasClass(\"active\")) {\r\n");
      out.write("\t\t\t\t\ttype = $(this).val();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\tif(name == null || name == '')\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\tvar data = {name : name, desc : desc, type : type};\r\n");
      out.write("\t\t\tvar url = 'database?");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${WebConstants.ACTION_NAME}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write('=');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${WebConstants.DO_SAVE_DATABASE}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("';\r\n");
      out.write("\t\t\tapp.ajaxCall({url : url, data : data, callbackFn : function(data, textStatus, jqXHR) {\r\n");
      out.write("\t\t\t\tloadDatabaseList();\r\n");
      out.write("\t\t\t\t$newDBModal.modal('hide');\r\n");
      out.write("\t\t\t}});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$newDBModal.modal();\r\n");
      out.write("\t});\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_fmt_005fmessage_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f0.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f0.setParent(null);
    // /apps/database/main.js.jsp(33,16) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f0.setKey("status.inactive");
    int _jspx_eval_fmt_005fmessage_005f0 = _jspx_th_fmt_005fmessage_005f0.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f0);
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f1 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f1.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f1.setParent(null);
    // /apps/database/main.js.jsp(34,14) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f1.setKey("database.type.subscribe");
    int _jspx_eval_fmt_005fmessage_005f1 = _jspx_th_fmt_005fmessage_005f1.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f1);
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f2 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f2.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f2.setParent(null);
    // /apps/database/main.js.jsp(36,13) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f2.setKey("status.active");
    int _jspx_eval_fmt_005fmessage_005f2 = _jspx_th_fmt_005fmessage_005f2.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f2);
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f3 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f3.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f3.setParent(null);
    // /apps/database/main.js.jsp(38,11) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f3.setKey("database.type.unsubscribe");
    int _jspx_eval_fmt_005fmessage_005f3 = _jspx_th_fmt_005fmessage_005f3.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f3);
    return false;
  }
}
